#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
tvh_priv=$YNH_APP_ARG_TVH_PRIV

if [ $tvh_priv -eq 1 ]
then
    args="-f -6"
    superuser=$YNH_APP_ARG_SUPERUSER
    password=$YNH_APP_ARG_PASSWORD
else
    args="-f -6 --noacl"
fi

app=$YNH_APP_INSTANCE_NAME

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_script_progression --message="Validating installation parameters.. $tvh_priv ." --weight=1

final_path=/opt/yunohost/tvheadend

test ! -e "$final_path" || ynh_die --message="The path $final_path already contains a folder"

# Register (book) web path
ynh_webpath_register --app=$app --domain=$domain --path_url=$path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_script_progression --message="Storing installation settings..." --weight=1

ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=path --value=$path_url

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# FIND AND OPEN PORTS
#=================================================
ynh_script_progression --message="Configuring firewall..."  --weight=4

# Find a free port for the web server
port=$(ynh_find_port --port=9981)
ynh_app_setting_set --app=$app --key=port --value=$port

# Find a free port for the streaming server
stream_port=$(ynh_find_port --port=9982)
# Open this port
ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $stream_port
ynh_app_setting_set --app=$app --key=stream_port --value=$stream_port

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression --message="Configuring system user..." --weight=2

# datadir is homedir as tvheadend stores all data in home dir
datadir=/home/yunohost.app/hts
ynh_app_setting_set --app=$app --key=datadir --value=$datadir

# Create a system user
ynh_system_user_create --username=$app --home_dir="$datadir"

#=================================================
# CREATE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Creating a data directory..." --weight=1

mkdir -p $datadir

chmod 750 "$datadir"
chmod -R o-rwx "$datadir"
chown -R $app:www-data "$datadir"

#=================================================
# INSTALL TVHEADEND
#=================================================
ynh_script_progression --message="Installing dependencies and app ...." --weight=8
myynh_install

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Configuring NGINX web server..." --weight=4

# Create a dedicated NGINX config
ynh_add_nginx_config

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression --message="Configuring a systemd service..." --weight=6
#args="-f -6 --noacl"

log_file="/var/log/$app.log"
ynh_add_systemd_config

#=================================================
# MODIFY A CONFIG FILE
#=================================================
if [ $tvh_priv -eq 1 ]
then
    ynh_script_progression --message="Setup config file..."
    mkdir -p "$datadir/.hts/tvheadend"
    ynh_add_config --template="../conf/superuser" --destination="$datadir/.hts/tvheadend/superuser"
fi

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression --message="Configuring log rotation..." --weight=1

# Use logrotate to manage application logfile(s)
#mkdir /var/log/$app
touch $log_file
chmod 666 $log_file
ynh_use_logrotate --logfile="$log_file"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --weight=1

yunohost service add $app --description="TV streaming server" --log="$log_file" --needs_exposed_ports "$stream_port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=2

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="$log_file"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_script_progression --message="Configuring SSOwat..." --weight=1

ynh_app_setting_set --app=$app --key=skipped_uris --value="/"

#=================================================
# RELOAD NGINX
#=================================================
ynh_script_progression --message="Reloading NGINX web server..." --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of Tvheadend completed, HTTP port is $port and HTSP port is $stream_port" --last
