#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --time --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
#superuser=$(ynh_app_setting_get --app=$app --key=superuser)
#password=$(ynh_app_setting_get --app=$app --key=password)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
port=$(ynh_app_setting_get --app=$app --key=port)
stream_port=$(ynh_app_setting_get --app=$app --key=stream_port)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	ynh_script_progression --message="Removing $app service integration..." --time --weight=1
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..." --time --weight=1

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..." --time --weight=1

# Remove the app-specific logrotate config
ynh_remove_logrotate

ynh_script_progression --message="Removing $app log file..." --time --weight=1

# Remove the log files
ynh_secure_remove --file="/var/log/$app.log"

#=================================================
# REMOVE TVHEADEND
#=================================================
#ynh_script_progression --message="Removing tvheadend-data..." --time --weight=6
#ynh_package_autopurge tvheadend-data
#ynh_script_progression --message="Removing dtv-scan-tables..." --time --weight=6
#ynh_package_autopurge dtv-scan-tables

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --time --weight=3

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

ynh_package_autopurge dtv-scan-tables
ynh_package_autopurge tvheadend-data

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing app main directory..." --time --weight=1

ynh_secure_remove --file=$final_path

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..." --time --weight=1

# Remove the dedicated NGINX config
ynh_remove_nginx_config

#=================================================
# CLOSE TVHEADEND PORTS
#=================================================

if yunohost firewall list | grep -q "\- $stream_port$"
then
    ynh_script_progression --message="Closing port $stream_port..." --time --weight=8
    ynh_exec_warn_less yunohost firewall disallow TCP $stream_port
fi


#=================================================
# REMOVE APP MAIN DIR AND CONFIG FILES
#=================================================
ynh_script_progression --message="Removing Tvheadend main directory and config files..." --time --weight=2

# Remove the app directory securely (/home/hts folder)
#ynh_secure_remove --file="$final_path"
#ynh_secure_remove --file="/etc/default/tvheadend"

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated hts system user..." --time --weight=1

# Delete a system user
ynh_system_user_delete --username=$app


# END OF SCRIPT
#=================================================
ynh_script_progression --message="Removal of Tvheadend completed" --last
