#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================
# Exit if an error occurs during the execution of the script
ynh_abort_if_errors

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
path_url=$(ynh_app_setting_get --app=$app --key=path)
#superuser=$(ynh_app_setting_get --app=$app --key=superuser)
#password=$(ynh_app_setting_get --app=$app --key=password)
final_path=$(ynh_app_setting_get --app=$app --key=final_path)
port=$(ynh_app_setting_get --app=$app --key=port)
stream_port=$(ynh_app_setting_get --app=$app --key=stream_port)
datadir=$(ynh_app_setting_get --app=$app --key=datadir)

#=================================================
# CHECK IF THE APP CAN BE RESTORED
#=================================================
ynh_script_progression --message="Validating restoration parameters..." --weight=16

test ! -d $final_path \
    || ynh_die --message="There is already a directory: $final_path "

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# RESTORE THE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Restoring NGINX web server configuration..." --weight=1

ynh_restore_file --origin_path="/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# RECREATE THE DEDICATED USER
#=================================================
ynh_script_progression --message="Recreating the dedicated system user..." --time --weight=1

# Create the dedicated user (if not existing)
ynh_system_user_create --username=$app --home_dir="$datadir"

#=================================================
# RESTORE THE MAIN DIRS
#=================================================
ynh_script_progression --message="Restoring the main directories..." --time --weight=1

ynh_restore_file --origin_path=$final_path

ynh_restore_file --origin_path=/usr/share/tvheadend/
ynh_restore_file --origin_path=/usr/share/dvb/

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression --message="Restoring the data directory..." --time --weight=1

ynh_restore_file --origin_path="$datadir" --not_mandatory

#siwi: check, ob folgende Kommandos notwendig sind, weil nicht vom restore erledigt
#mkdir -p $datadir

#chmod 750 "$datadir"
#chmod -R o-rwx "$datadir"
#chown -R $app:www-data "$datadir"
#=================================================
# OPEN TVHEADEND PORTS
#=================================================
if yunohost firewall list | grep -q "\- $port$"
then
    ynh_die --message="Port $port already open (and maybe used by another application)"
fi

if yunohost firewall list | grep -q "\- $stream_port$"
then
    ynh_die --message="Port $stream_port already open (and maybe used by another application)"
fi

ynh_exec_warn_less yunohost firewall allow --no-upnp TCP $stream_port

#=================================================
# SPECIFIC RESTORATION
#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_script_progression --message="Installing dependencies..." --weight=7

if [ -n "$(uname -m | grep arm)" ]
then
    ynh_install_app_dependencies $pkg_dependencies_arm
else
    ynh_install_app_dependencies $pkg_dependencies_x86
fi

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression --message="Restoring the systemd configuration..." --time --weight=1

ynh_restore_file --origin_path="/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

#=================================================
# RESTORE THE LOGROTATE CONFIGURATION AND LOG FILE
#=================================================
ynh_script_progression --message="Restoring logrotate configuration and log file..." --weight=1

ynh_restore_file --origin_path="/etc/logrotate.d/$app"

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression --message="Integrating service in YunoHost..." --time --weight=1

yunohost service add $app --description="TV streaming server" --log="/var/log/$app.log" --needs_exposed_ports "$stream_port"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting Tvheadend service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app.log"

#=================================================
# GENERIC FINALIZATION
#=================================================
# RELOAD NGINX 
#=================================================
ynh_script_progression --message="Reloading NGINX web server and PHP-FPM..." --time --weight=1

ynh_systemd_action --service_name=nginx --action=reload

#=================================================
# PREVENT TVHEADEND BEING UPGRADED THROUGHT APT
#=================================================
ynh_script_progression --message="Prevent Tvheadend being upgraded throught APT..." --weight=1

apt-mark hold tvheadend

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of Tvheadend completed, HTTP port is $port and HTSP port is $stream_port" --last

